### ISSUE TITLE
Owned Vehicles

### ISSUE THREAD

**Issue by theenack** [QuantumMalice/qb-platescan#1]
When scanning an owned vehicle getting a few different errors. All in relation to the if results string.

[ script:qb-platescan] SCRIPT ERROR: @qb-platescan/server/sv_main.lua:39: attempt to index a nil value (field '?')
[ script:qb-platescan] > GetWarrantStatus (@qb-platescan/server/sv_main.lua:39)
[ script:qb-platescan] > handler (@qb-platescan/server/sv_main.lua:91)
[ script:qb-platescan] > <unknown> (@oxmysql/dist/build.js:22247)
[ script:qb-platescan] > processTicksAndRejections (node:internal/process/task_queues:96)
[ script:qb-platescan] > async rawQuery (@oxmysql/dist/build.js:22237)

**Comment by QuantumMalice** [comment]
Ah yes, sorry for the delay and thank you for your patience.

I have heard of this issue from quite a few people. Someone from the project sloth discord left some snippets to fix this and it worked for many others, maybe it will work for you also. I have attached a zip containing a replacement for the server.lua file, let me know if this solves your problem.

[sv_main.lua.zip](https://github.com/QuantumMalice/qb-platescan/files/10080438/sv_main.lua.zip)
